---
title: "Lingustics Preliminary Analysis"
author: "Josiah Gilbert"
date: "2023-03-20"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(table1)
library(tidyverse)
library(readxl)
library(ordinal)
library(foreign)
library(ggplot2)
library(MASS)
library(Hmisc)
library(reshape2)
library(scales)
library(AER)
library(modelsummary)
```

## 0 Reading data and cleaning

```{r}
ling_full <- read_csv("Study Responses (Final Fixed).csv") %>% 
  rename(overall_in = `-in usage`,
         gender_effect = `-in usage w/ gender`,
         area_type = `Type of Area`,
         romantic = `Romantic Partner`,
         close = `Close friend`,
         acquaintance = `Acquaintance/Stranger`,
           parent_guard = `Parent/Guardian`) %>%
  mutate(overall_in = factor(overall_in, levels = c("I never drop the 'g' on -ing ending words", "I rarely drop the 'g' on -ing ending words", "I sometimes drop the 'g' on -ing ending words", "I often drop the 'g' on -ing ending words", "I drop the 'g' on -ing ending word multiples times a day")))

# removes column with long column name, and several other unneeded columns
ling_full <- ling_full[,c(-13, -17, -29, -30)]


ling <- ling_full  %>% 
  filter(Gender != "Non-Binary" & Region %in% c("Northeast", "Southeast")) %>% 
  mutate(Education = case_match(Education,
                                c("Currently in College", "Some High School, no Diploma",
                                  "High School") ~ "No degree",
                                c("Masters Degree", "Bachelors Degree", "PhD") ~ "Degree")) %>% 
  mutate(overall_in = case_match(as.character(overall_in),
                                c("I never drop the 'g' on -ing ending words",
                                  "I rarely drop the 'g' on -ing ending words")
                                ~ "I rarely drop the 'g' on -ing ending words",
                                "I sometimes drop the 'g' on -ing ending words"
                                ~ "I sometimes drop the 'g' on -ing ending words",
                                c("I often drop the 'g' on -ing ending words",
                                  "I drop the 'g' on -ing ending word multiples times a day") ~ 
                                  "I often drop the 'g' on -ing ending words")) %>% 
  mutate(overall_in = factor(overall_in, levels = c("I rarely drop the 'g' on -ing ending words", "I sometimes drop the 'g' on -ing ending words", "I often drop the 'g' on -ing ending words"))) %>% 
  mutate(Ethnicity = case_match(Ethnicity, "White" ~ "White", .default = "Minority"))



ling$Region = factor(ling$Region, levels = c("Northeast", "Southeast"))
ling$Gender  = factor(ling$Gender)
ling$Ethnicity = as.factor(ling$Ethnicity)
ling$Education = as.factor(ling$Education)





```

```{r}
table1(~Ethnicity + Education + area_type + Gender + Age + Region, data = ling)

# drop non-binary individual
# in-college vs. w/ college degree (masters + bachelors), only 1 in less than high school and in just high school
# area_type okay, at least 5 in each category
# Ethnicity... tempted to drop term entirely otherwise need to only use white (n=22) b/c 2 or less in all other categories
```


```{r}
# table with lumped data
table1(~overall_in|Region, data = ling_mod)

#combine never and rarely, combine often and drop

ling_full$overall_in

```


```{r}
boxplot(ling$Age)
```


```{r data for 2nd research question}
ling_long_situation <- ling_full %>%
  mutate(person_id = 1:nrow(ling_full)) %>%
  pivot_longer(cols = c(romantic:parent_guard, Boss), names_to = "Situation", values_to = "situation_in_usage") %>% 
  filter(is.na(situation_in_usage) == FALSE) %>% 
  mutate(Situation = case_match(Situation, "Boss"~"Boss",
                                "acquaintance" ~ "Acquaintance",
                                "parent_guard" ~ "Parent or Guardian",
                                "close" ~ "Close friend",
                                "romantic" ~ "Romantic partner")) %>% 
  mutate(Situation = factor(Situation, levels = c("Boss", "Acquaintance", "Parent or Guardian", "Close friend", "Romantic partner")))
```

```{r data for 3rd research question}
ling_long_word <- ling %>% 
  mutate(person_id = 1:nrow(ling)) %>% 
  pivot_longer(cols = Doing:Warning, names_to = "Word", values_to = "in_freq")
```

## 1 Exploratory plotting and tables

```{r Yang_plot1}
region <- ggplot( ling, aes(x=" ", y=Region,fill = Region)) +
  geom_bar(stat="identity", width=1) +
  coord_polar("y", start=0) + theme_void()
```


```{r Yang_plot2}
ethnicity<- ling %>% 
ggplot()+
  geom_bar(aes(x = Ethnicity), position = "dodge")+
  theme_classic()+
  ylab("Count")+ theme(axis.text.x = element_text(angle = 45, vjust = 0.4))
```


```{r Yang_plot3}
edu<- ling %>% 
ggplot()+
  geom_bar(aes(x = Education), position = "dodge")+
  theme_classic()+
  ylab("Count")

```


```{r Yang_plot4}
age <- ling %>% 
ggplot()+
  geom_bar(aes(x = Age), position = "dodge")+
  theme_classic()+
  ylab("Count")

```


```{r Yang_plot5}
SI <-  factor(ling_long_situation[['situation_in_usage']],labels=c("Not likely to or never  drop the 'g'", "Rarely drop the 'g' ","Sometimes drop the 'g'",  "Often drop the 'g'"  ,"Very likely to or always drop the 'g' all the time"))

ling_long_situation %>% group_by(Situation, situation_in_usage) %>% 
ggplot()+
  geom_bar(aes(x = Situation,  fill = SI), position = "dodge")+
  theme_classic()+
  ylab("")+
  labs(fill = "Frequency of dropping -g")


```


```{r}
ling %>% 
ggplot()+
  geom_bar(aes(x = Region, fill = overall_in), position = "dodge")+
  theme_classic()+
  ylab("Frequency of dropping -g")+
  labs(fill = "Frequency of dropping -g")
```

```{r}
ling_region <- ling %>%
  group_by(Region, overall_in) %>%
  count(name = "counts") %>% 
  group_by(Region) %>% 
  mutate("percent" = counts/sum(counts)) %>% 
  ungroup() %>% 
  mutate("percent_answers_lab" = percent(percent, accuracy = 1)) %>% 
  mutate(overall_in = factor(overall_in, levels = c("I often drop the 'g' on -ing ending words", "I sometimes drop the 'g' on -ing ending words", "I rarely drop the 'g' on -ing ending words")))

region_order <- ling_region %>% 
  filter(overall_in == 1) %>% 
  arrange(desc(percent)) %>% 
  dplyr::pull(Region)

ling_region <- ling_region %>% 
  mutate(Word = factor(Region, levels = region_order))


ling_region %>%
  ggplot(aes(y = percent, x = Region, fill =  as.factor(overall_in)))+
  geom_col()+
  coord_flip()+
  theme_minimal()+
  scale_x_discrete()+
  scale_fill_manual(breaks = c("I rarely drop the 'g' on -ing ending words", "I sometimes drop the 'g' on -ing ending words", "I often drop the 'g' on -ing ending words"), #"5", "4", "3", "2", "1"
                    values = c(
                      "I often drop the 'g' on -ing ending words" = "darkorange3",
                      "I sometimes drop the 'g' on -ing ending words" = "forestgreen",
                      "I rarely drop the 'g' on -ing ending words" = "deepskyblue4"
                    )) +
  # geom_text(aes(label = percent_answers_lab),
  #           position = position_stack(vjust = 0.5),
  #           color = "white",
  #           fontface = "bold") +
  labs(title = "Frequency of dropping the 'g' in -ing endings by region",
       x = NULL,
       fill = NULL) +
   theme(axis.text.x = element_blank(),
        axis.title.x = element_blank(),
        panel.grid = element_blank(),
        legend.position = "top")

```

```{r}
ling_area <- ling %>%
  group_by(area_type, overall_in) %>%
  count(name = "counts") %>% 
  group_by(area_type) %>% 
  mutate("percent" = counts/sum(counts)) %>% 
  ungroup() %>% 
  mutate("percent_answers_lab" = percent(percent, accuracy = 1)) %>% 
  mutate(overall_in = factor(overall_in, levels = c("I often drop the 'g' on -ing ending words", "I sometimes drop the 'g' on -ing ending words", "I rarely drop the 'g' on -ing ending words")))


ling_area <- ling_area %>% 
  mutate(area_type = factor(area_type, levels = c("Suburban", "Urban", "Rural")))


ling_area %>%
  ggplot(aes(y = percent, x = area_type, fill =  as.factor(overall_in)))+
  geom_col()+
  coord_flip()+
  theme_minimal()+
  scale_x_discrete()+
  scale_fill_manual(breaks = c("I rarely drop the 'g' on -ing ending words", "I sometimes drop the 'g' on -ing ending words", "I often drop the 'g' on -ing ending words"), #"5", "4", "3", "2", "1"
                    values = c(
                      "I often drop the 'g' on -ing ending words" = "darkorange3",
                      "I sometimes drop the 'g' on -ing ending words" = "forestgreen",
                      "I rarely drop the 'g' on -ing ending words" = "deepskyblue4"
                    )) +
  # geom_text(aes(label = percent_answers_lab),
  #           position = position_stack(vjust = 0.5),
  #           color = "white",
  #           fontface = "bold") +
  labs(title = "Frequency of dropping the 'g' in -ing endings by type of area",
       x = NULL,
       fill = NULL) +
   theme(axis.text.x = element_blank(),
        axis.title.x = element_blank(),
        panel.grid = element_blank(),
        legend.position = "top")

```




```{r}
ling_long_situation_percent <- ling_long_situation %>%
  mutate(situation_in_usage = factor(situation_in_usage, levels = c("5", "4", "3", "2", "1"))) %>% 
  group_by(Situation, situation_in_usage) %>%
  count(name = "counts") %>% 
  group_by(Situation) %>% 
  mutate("percent" = counts/sum(counts)) %>% 
  ungroup() %>% 
  mutate("percent_answers_lab" = percent(percent, accuracy = 1))

situation_order <- ling_long_situation_percent %>% 
  filter(situation_in_usage == 1) %>% 
  arrange(desc(percent)) %>% 
  dplyr::pull(Situation)

ling_long_situation_percent <- ling_long_situation_percent %>% 
  mutate(Situation = factor(Situation, levels = situation_order))


ling_long_situation_percent %>%
  ggplot(aes(y = percent, x = Situation, fill =  as.factor(situation_in_usage)))+
  geom_col()+
  coord_flip()+
  theme_minimal()+
  scale_x_discrete()+
  scale_fill_manual(breaks = c("1", "2", "3", "4", "5"), #"5", "4", "3", "2", "1"
                    values = c(
                      "5" = "darkorange3",
                      "4" = "orange",
                      "3" = "forestgreen",
                      "2" = "deepskyblue",
                      "1" = "deepskyblue4"
                    )) +
  # geom_text(aes(label = percent_answers_lab),
  #           position = position_stack(vjust = 0.5),
  #           color = "white",
  #           fontface = "bold") +
  labs(title = "Frequency of dropping the 'g' in -ing endings by conversation situation",
       x = NULL,
       fill = NULL) +
   theme(axis.text.x = element_blank(),
        axis.title.x = element_blank(),
        panel.grid = element_blank(),
        legend.position = "top")



```

```{r}
ling_long_word %>% 
  ggplot()+
  geom_boxplot(aes(x = Word, y = in_freq))+
  theme_classic()+
  ylab("Frequency of dropping -g")
```

```{r}
ling_long_word_percent <- ling_long_word %>%
  mutate(in_freq = factor(in_freq, levels = c("5", "4", "3", "2", "1"))) %>% 
  group_by(Word, in_freq) %>%
  count(name = "counts") %>% 
  group_by(Word) %>% 
  mutate("percent" = counts/sum(counts)) %>% 
  ungroup() %>% 
  mutate("percent_answers_lab" = percent(percent, accuracy = 1))

word_order <- ling_long_word_percent %>% 
  filter(in_freq == 1) %>% 
  arrange(desc(percent)) %>% 
  dplyr::pull(Word)

ling_long_word_percent <- ling_long_word_percent %>% 
  mutate(Word = factor(Word, levels = word_order))


ling_long_word_percent %>%
  ggplot(aes(y = percent, x = Word, fill =  as.factor(in_freq)))+
  geom_col()+
  coord_flip()+
  theme_minimal()+
  scale_x_discrete()+
  scale_fill_manual(breaks = c("1", "2", "3", "4", "5"), #"5", "4", "3", "2", "1"
                    values = c(
                      "5" = "darkorange3",
                      "4" = "orange",
                      "3" = "forestgreen",
                      "2" = "deepskyblue",
                      "1" = "deepskyblue4"
                    )) +
  # geom_text(aes(label = percent_answers_lab),
  #           position = position_stack(vjust = 0.5),
  #           color = "white",
  #           fontface = "bold") +
  labs(title = "Frequency of dropping the 'g' in -ing endings by word",
       x = NULL,
       fill = NULL) +
   theme(axis.text.x = element_blank(),
        axis.title.x = element_blank(),
        panel.grid = element_blank(),
        legend.position = "top")



```


```{r}
table1(~Region + Age + Ethnicity + Education + Gender + area_type|overall_in, data = ling)
```

```{r}
table1(~overall_in + Age + Ethnicity + Education + Gender + area_type|Region, data = ling)
```

## 2 Modeling

```{r model for 1st research question}

model1 <- polr(as.factor(overall_in) ~ Region + Age + area_type + Gender + Ethnicity + Education, Hess=TRUE, data = ling)

summary(model1)


# finds p-values, polr doesn't automatically find them
tidy_custom.polr <- function(x, ...) {
  s <- coeftest(x)
  out <- data.frame(
    term = row.names(s),
    p.value = s[, "Pr(>|z|)"])
  out
}

p_values <- tidy_custom.polr(model1)[1:7,]

rownames(p_values) <- NULL

p_values
```

```{r forest plot for first model}
intervals_1 <- data.frame(confint(model1)) %>% 
  rownames_to_column() %>%
  mutate(estimate = exp(coef(model1)))

colnames(intervals_1) <- c("variable", "lower", "upper", "estimate")

intervals_renamed_1 <- intervals_1 %>% 
  mutate(variable = case_match(variable, "EducationNo degree" ~ "Degree not completed vs. Degree",
                               "EthnicityWhite" ~ "White vs. Minority",
                               "area_typeUrban" ~ "Urban vs. Rural",
                               "area_typeSuburban" ~ "Suburban vs. Rural",
                               "RegionSoutheast" ~ "Southeast vs. Northeast",
                               "GenderMale" ~ "Male vs. Female",
                               "Age" ~ "Age"))

# untransformed forest plot

ggplot(intervals_renamed_1) + 
  geom_errorbarh(aes(y = variable, xmin = lower, xmax = upper), height = 0.1)+
  geom_vline(xintercept = 0, color = "black", linetype = "dashed")+
  theme_classic()+
  ylab("Variable")+
  ggtitle("Confidence intervals for variables")

# transformed forest plot

ggplot(intervals_renamed_1) + 
  geom_errorbarh(aes(y = variable, xmin = exp(lower), xmax = exp(upper)), height = 0.1)+
  geom_vline(xintercept = 1, color = "black", linetype = "dashed")+
  theme_classic()+
  ylab("Variable")+
  ggtitle("Confidence intervals for variables")

# transformed zoomed in forest plot

ggplot(intervals_renamed_1 %>% filter(variable == "Urban vs. Rural"| variable == "Suburban vs. Rural" | variable == "Male vs. Female" | variable == "Degree not completed vs. Degree"|variable == "Age")) + 
  geom_errorbarh(aes(y = variable, xmin = exp(lower), xmax = exp(upper)), height = 0.1)+
  geom_vline(xintercept = 1, color = "black", linetype = "dashed")+
  theme_classic()+
  ylab("Variable")+
  ggtitle("Confidence intervals (detail) for variables")

```


```{r model for 2nd research question}
model2 <- clmm(as.factor(situation_in_usage) ~ Situation + (1|person_id), data = ling_long_situation)

summary(model2)

intervals_2 <- data.frame(confint(model2)) %>% 
  rownames_to_column() %>%
  mutate(estimate = exp(coef(model2))) %>% 
  filter(!row_number() %in% c(1,2,3,4))

colnames(intervals_2) <- c("variable", "lower", "upper", "estimate")

intervals_renamed_2 <- intervals_2 %>% 
  mutate(variable = case_match(variable, "SituationAcquaintance" ~ "Acquaintance vs. Boss",
                               "SituationParent or Guardian" ~ "Parent or Guardian vs. Boss",
                               "SituationClose friend" ~ "Close friend vs. Boss",
                               "SituationRomantic partner" ~ "Romantic partner vs. Boss")) %>% 
  mutate(variable = factor(variable, levels = c("Romantic partner vs. Boss", "Close friend vs. Boss",  "Parent or Guardian vs. Boss", "Acquaintance vs. Boss")))

# untransformed forest plot

ggplot(intervals_renamed_2) + 
  geom_errorbarh(aes(y = variable, xmin = lower, xmax = upper), height = 0.1)+
  geom_vline(xintercept = 0, color = "black", linetype = "dashed")+
  theme_classic()+
  ylab("Situation")+
  ggtitle("Confidence intervals for situations")

# transformed forest plots

ggplot(intervals_renamed_2) + 
  geom_errorbarh(aes(y = variable, xmin = exp(lower), xmax = exp(upper)), height = 0.1)+
  geom_vline(xintercept = 1, color = "black", linetype = "dashed")+
  theme_classic()+
  ylab("Situation")+
  ggtitle("Confidence interval situations")

# zoomed in transformed forest plot

ggplot(intervals_renamed_2 %>% filter(variable == "Acquaintance vs. Boss")) + 
  geom_errorbarh(aes(y = variable, xmin = exp(lower), xmax = exp(upper)), height = 0.1)+
  geom_vline(xintercept = 1, color = "black", linetype = "dashed")+
  theme_classic()+
  ylab("Situation")+
  ggtitle("Confidence interval (detail) for Acquaintance vs. Boss")


intervals
```

```{r forest plot for model 3}
intervals_3 <- data.frame(confint(model3)) %>% 
  rownames_to_column() %>%
  mutate(estimate = exp(coef(model3))) %>% 
  filter(!row_number() %in% c(1,2,3,4))

colnames(intervals_3) <- c("variable", "lower", "upper", "estimate")

intervals_renamed_3 <- intervals_3 %>% 
  mutate(variable = case_match(variable, "WordAnything" ~ "Anything vs. Admitting",
                               "WordDeveloping" ~ "Developing vs. Admitting",
                               "WordDoing" ~ "Doing vs. Admitting",
                               "WordEnding" ~ "Ending vs. Admitting",
                               "WordFeeling" ~ "Feeling vs. Admitting",
                               "WordNothing" ~ "Nothing vs. Admitting",
                               "WordShopping" ~ "Shopping vs. Admitting",
                               "WordSomething" ~ "Something vs. Admitting",
                               "WordStruggling" ~ "Struggling vs. Admitting",
                               "WordTalking" ~ "Talking vs. Admitting",
                               "WordWarning" ~ "Warning vs. Admitting"))

# untransformed forest plot

ggplot(intervals_renamed_3) + 
  geom_errorbarh(aes(y = variable, xmin = lower, xmax = upper), height = 0.1)+
  geom_vline(xintercept = 0, color = "black", linetype = "dashed")+
  theme_classic()+
  ylab("Words")+
  ggtitle("Confidence intervals for words")

# transformed forest plot

ggplot(intervals_renamed_3) + 
  geom_errorbarh(aes(y = variable, xmin = exp(lower), xmax = exp(upper)), height = 0.1)+
  geom_vline(xintercept = 1, color = "black", linetype = "dashed")+
  theme_classic()+
  ylab("Words")+
  ggtitle("Confidence intervals for words")

# zoomed in transformed forest plot

ggplot(intervals_renamed_3 %>% filter(variable == "Warning vs. Admitting" | variable  == "Ending vs. Admitting" | variable == "Developing vs. Admitting"| variable == "Anything vs. Admitting")) +
  geom_errorbarh(aes(y = variable, xmin = exp(lower), xmax = exp(upper)), height = 0.1)+
  geom_vline(xintercept = 1, color = "black", linetype = "dashed")+
  theme_classic()+
  ylab("Words")+
  ggtitle("Confidence intervals (detail) for words")


intervals_3
```



```{r interpretation for model 1}
m1 <- polr( overall_in  ~ Region + Age + Gender + Ethnicity  + Education, data = ling , Hess = TRUE)
 

## store table
(ctable1 <- coef(summary(m1)))

## calculate and store p values
p <- pnorm(abs(ctable1[, "t value"]), lower.tail = FALSE) * 2

## odds ratios
Oddsratio <- exp(coef(m1))

## combined table--Reg 1
(ctable1 <- cbind(ctable1, "p value" = p, "Odds ratio" = Oddsratio))

write.table(ctable1, file = 'Table/Table1_1.csv', col.names = TRUE,
             row.names = TRUE, sep = ",")




#  convert the coefficients into odds ratios. To get the OR and confidence intervals, we just exponentiate the estimates and confidence intervals.
ci1 <- confint(m1) # default method gives profiled CIs

confint.default(m1) # CIs assuming normality
## OR and CI
OR_CI1 <- exp(cbind(OR = coef(m1), ci1))

write.table(OR_CI1, file = 'Table/Table1_2.csv', col.names = TRUE,
             row.names = TRUE, sep = ",")

```


```{r interpretation for model 2}
m2 <- clmm(as.factor(situation_in_usage) ~ Situation + Gender + Region + Age + overall_in + Ethnicity + (1|person_id), data = ling_long_situation)

## store table
(ctable2 <- coef(summary(m2)))

## calculate and store p values
#p2 <- pnorm(abs(ctable2[, "t value"]), lower.tail = FALSE) * 2

## odds ratios
Oddsratio2 <- exp(coef(m2))

## combined table--Reg 1
(ctable2 <- cbind(ctable2, "Odds ratio" = Oddsratio2))



#  convert the coefficients into odds ratios. To get the OR and confidence intervals, we just exponentiate the estimates and confidence intervals.
ci2 <- confint(m2) # default method gives profiled CIs

confint.default(m2) # CIs assuming normality
## OR and CI
OR_CI2 <- exp(cbind(OR = coef(m2), ci2))


write.table(ctable2, file = 'Table/Table2_1.csv', col.names = TRUE,
             row.names = TRUE, sep = ",")
write.table(OR_CI2, file = 'Table/Table2_2.csv', col.names = TRUE,
             row.names = TRUE, sep = ",")

```


```{r interpretation for model 3}
m3 <- clmm(as.factor(in_freq) ~ Word + Gender + Region + Age + Ethnicity + Education + overall_in + (1|person_id), data = ling_long_word)

## store table
(ctable3 <- coef(summary(m3)))

## calculate and store p values
#p2 <- pnorm(abs(ctable2[, "t value"]), lower.tail = FALSE) * 2

## odds ratios
Oddsratio3 <- exp(coef(m3))

## combined table--Reg 1
(ctable3 <- cbind(ctable3, "Odds ratio" = Oddsratio3))



#  convert the coefficients into odds ratios. To get the OR and confidence intervals, we just exponentiate the estimates and confidence intervals.
ci3 <- confint(m3) # default method gives profiled CIs

confint.default(m3) # CIs assuming normality
## OR and CI
OR_CI3 <- exp(cbind(OR = coef(m3), ci3))

write.table(ctable3, file = 'Table/Table3_1.csv', col.names = TRUE,
             row.names = TRUE, sep = ",")
write.table(OR_CI3, file = 'Table/Table3_2.csv', col.names = TRUE,
             row.names = TRUE, sep = ",")

```
